name: testing for PR

on:
  push:
    branches:
      - test

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - uses: microsoft/Teams-MSGraph-Samples/actions/msteams-send-message@v1
        with:
          teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          message: "New pull request opened"
          summary: "Pull Request opened by"
