name: testing for PR

on:
  push:
    branches:
      - test

jobs:
  send_message:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Teams
        run: |
          curl -H "Content-Type: application/json" -d '{"text": "New pull request opened"}' ${{ secrets.TEAMS_WEBHOOK_URL }}
